# Generated by Django 3.2.5 on 2021-09-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Fecha_Nacimiento',
            field=models.DateField(help_text='Ejemplo: 08/04/1999', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Telefono',
            field=models.CharField(max_length=10),
        ),
    ]
